name: metrics

on:
  schedule:
    - cron: '0 1-23 * * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub metrics as SVG image
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SECRET }}  
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_languages: yes
          plugin_languages_colors: "0:blue, 1:yellow, 2:green, 3:orange, 4:black"  
          plugin_lines: yes
          config_timezone: Europe/Paris 
